# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1183, 732)
        self.window_3 = QtWidgets.QWidget(MainWindow)
        self.window_3.setObjectName("window_3")
        self.graph = QChartView(self.window_3)
        self.graph.setGeometry(QtCore.QRect(0, 0, 911, 681))
        self.graph.setObjectName("graph")
        self.info = QtWidgets.QListWidget(self.window_3)
        self.info.setGeometry(QtCore.QRect(910, 0, 261, 301))
        self.info.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.info.setObjectName("info")
        item = QtWidgets.QListWidgetItem()
        self.info.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.info.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.info.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.info.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.info.addItem(item)
        self.suggest = QtWidgets.QPlainTextEdit(self.window_3)
        self.suggest.setGeometry(QtCore.QRect(910, 300, 261, 381))
        self.suggest.setReadOnly(True)
        self.suggest.setObjectName("suggest")
        MainWindow.setCentralWidget(self.window_3)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1183, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.info.isSortingEnabled()
        self.info.setSortingEnabled(False)
        item = self.info.item(0)
        item.setText(_translate("MainWindow", "个人情况"))
        item = self.info.item(1)
        item.setText(_translate("MainWindow", "姓名："))
        item = self.info.item(2)
        item.setText(_translate("MainWindow", "累计接尘量："))
        item = self.info.item(3)
        item.setText(_translate("MainWindow", "预计未来7天接尘量："))
        item = self.info.item(4)
        item.setText(_translate("MainWindow", "危险系数："))
        self.info.setSortingEnabled(__sortingEnabled)
from PyQt5.QtChart import QChartView
