# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1261, 736)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.list_widget_online = QtWidgets.QListWidget(self.centralwidget)
        self.list_widget_online.setGeometry(QtCore.QRect(0, 0, 381, 101))
        self.list_widget_online.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_widget_online.setObjectName("list_widget_online")
        item = QtWidgets.QListWidgetItem()
        self.list_widget_online.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_widget_online.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_widget_online.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_widget_online.addItem(item)
        self.list_widget_alert = QtWidgets.QTableWidget(self.centralwidget)
        self.list_widget_alert.setGeometry(QtCore.QRect(-10, 140, 391, 551))
        self.list_widget_alert.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_widget_alert.setObjectName("list_widget_alert")
        self.list_widget_alert.setColumnCount(3)
        self.list_widget_alert.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.list_widget_alert.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_widget_alert.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_widget_alert.setHorizontalHeaderItem(2, item)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(0, 100, 381, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.browser = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.browser.setGeometry(QtCore.QRect(379, -1, 881, 691))
        self.browser.setObjectName("browser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1261, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.list_widget_online.isSortingEnabled()
        self.list_widget_online.setSortingEnabled(False)
        item = self.list_widget_online.item(0)
        item.setText(_translate("MainWindow", "在线对象"))
        item = self.list_widget_online.item(1)
        item.setText(_translate("MainWindow", "工厂数量：0"))
        item = self.list_widget_online.item(2)
        item.setText(_translate("MainWindow", "工人数量：0"))
        item = self.list_widget_online.item(3)
        item.setText(_translate("MainWindow", "传感器数量：0"))
        self.list_widget_online.setSortingEnabled(__sortingEnabled)
        item = self.list_widget_alert.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "工厂名"))
        item = self.list_widget_alert.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "传感器编号"))
        item = self.list_widget_alert.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "浓度"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">浓度超标传感器预警名单</span></p></body></html>"))
from PyQt5 import QtWebEngineWidgets
